schemaVersion: 2.2.0
metadata:
  name: 'DO Portal_Backend - Staging'
attributes:
  space:
    instanceType: regular
    editor:
      type: Fleet
version: 1.0
services:
  backend:
    image: node:14
    environment:
      NODE_ENV: staging
      PORT: 3000
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:staging